spring:
  datasource:
    url: jdbc:${Postgres.DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    open-in-view: false
    hibernate:
      ddl-auto: create-drop