spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    open-in-view: false